export const NO_AUTH_ROUTE = 'NO_AUTH_ROUTE';
export const REFLECTOR = 'REFLECTOR';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const SEQUELIZE_CONSTRAINT_ERROR = 'SequelizeForeignKeyConstraintError';
export const STATES_REPOSITORY = 'STATES_REPOSITORY';
export const CITIES_REPOSITORY = 'CITIES_REPOSITORY';
export const POSTS_REPOSITORY = 'POSTS_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
